name: CI

on:
  create:
    tags: 
    - release/**
  push:
    branches:
    - main  
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      CORE_PACKAGE: 'Core/TypeIndicatorConverter.Core.csproj'
      SYS_JSON_PACKAGE: 'Text.Json/TypeIndicatorConverter.Text.Json.csproj'
      JSON_NET_PACKAGE: 'Json.Net/TypeIndicatorConverter.NewtonsoftJson.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          9.x.x
          8.x.x
  
    - name: Install dependencies 
      run: dotnet restore $CORE_PACKAGE && dotnet restore $SYS_JSON_PACKAGE && dotnet restore $JSON_NET_PACKAGE

    - name: Build
      run: dotnet build $CORE_PACKAGE --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION && dotnet build $SYS_JSON_PACKAGE --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION && dotnet build $JSON_NET_PACKAGE --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION

    - name: Run tests
      run: | 
        cd Unit.Tests
        dotnet test --configuration $BUILD_CONFIG --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/release')
      run: dotnet nuget push Core/bin/Release/*.nupkg -k ${{secrets.NUGET}} -s https://api.nuget.org/v3/index.json && dotnet nuget push Text.Json/bin/Release/*.nupkg -k ${{secrets.NUGET}} -s https://api.nuget.org/v3/index.json && dotnet nuget push Json.Net/bin/Release/*.nupkg -k ${{secrets.NUGET}} -s https://api.nuget.org/v3/index.json
    