name: CI

on:
  create:
    tags: 
    - release/**
  push:
    branches:
    - main  
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'TypeIndicatorConverter.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          9.x.x
          8.x.x
  
    - name: Install dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION

    - name: Run tests
      run: | 
        cd Unit.Tests
        dotnet test --configuration $BUILD_CONFIG --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET}}